color0 #111411
color1 #ffb4ab
color2 #7ada9d
color3 #b6ccb9
color4 #a3cddb
color5 #7ada9d
color6 #b6ccb9
color7 #e1e3de
color8 #8a938b
color9 #ffb4ab
color10 #7ada9d
color11 #b6ccb9
color12 #a3cddb
color13 #7ada9d
color14 #b6ccb9
color15 #e1e3de

cursor                #e1e3de
cursor_text_color     #111411
background            #111411
foreground            #e1e3de
selection_foreground  #c0c9c0
selection_background  #414942
active_border_color   #7ada9d
inactive_border_color #414942
url_color             #7ada9d

active_tab_foreground   #00391e
active_tab_background   #7ada9d
inactive_tab_foreground #c0c9c0
inactive_tab_background #414942
cursor_trail_color      #c0c9c0
